# Generated by Django 5.0.3 on 2024-06-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=255)),
                ("coins", models.CharField(default="", max_length=255)),
                ("receiver", models.TextField(default="")),
                ("hash", models.TextField(default="")),
                ("hash_link", models.TextField(default="")),
            ],
        ),
    ]
